### PR TITLE
fix: update cross-platform script to execute only when component is n…

### PR DESCRIPTION
**Pull request by wyseguyonline**
…ot inside an existing app

### CODE REVIEW

**Comment by wyseguyonline** [comment]
@StommePoes @JasonLantz @mhomolak

**Comment by aaronkaka** [comment]
My RegEx is a little rusty... what is it saying?

**Comment by wyseguyonline** [comment]
Look for the literal string 'node_modules' followed by any number of non-whitespace characters followed by another literal string 'node_modules'.  Essentially, see if we are running this script from within an application.

**Comment by StommePoes** [comment]
I'm stupid. What is being exec'd that this script is looking at?

Even in Drawer, anything running anything (including webpack) ends up calling something in node_modeles/whatever/node_modules.

**Comment by wyseguyonline** [comment]
It doesn't matter.  The problem is that when one of our archetype based components is in an application, it can't find the postinstall script because it is trying to run it from the root of the application, not the root of the component.  Will just have to rename the script so it isn't automatically invoked and update the documentation to have users run the script manually.

**Pull request closed without merging**
