### PR TITLE
fix: add copy-utils command to relevant scripts just in case the deve…

### PR DESCRIPTION
**Pull request by wyseguyonline**
…loper forgets

### CODE REVIEW

**Comment by wyseguyonline** [comment]
@StommePoes @JasonLantz @mhomolak @umahaea Please review.  A new version of this will need to be published prior to merging component-archetype and other components.

**Comment by StommePoes** [comment]
so... do we want to keep it listed in the other readme then? It seems now a redundant step.

**Comment by wyseguyonline** [comment]
Yeah, we can lose it in the documentation.

**Comment by StommePoes** [comment]
Does that mkdir command break on all our other components as well?

**Comment by wyseguyonline** [comment]
No.  I tested the dev-setup script and it the folder is created through the copy command without having to explicitly create it.

**Comment by wyseguyonline** [comment]
If there are no other questions or approvals, I'm going to merge and work through the release process.

**Pull request merged**
